aws_region="ap-south-1"
project_name="zomato"
project_environment="production"
vpc_cidr_block = "172.20.0.0/16"
enable_natgw=true
loadbalancer_ingress_ports = ["80","443"]
debug_backend = true
bastion_instance_type = "t3.micro"
bastion_ami_id = "ami-00d2dbb426772b03a"
backend_instance_type = "t3.micro"
asg_min_size = 0
asg_max_size = 0
asg_desired_size = 0
health_check_port = 80
deregistration_delay = 10
target_type = "instance"
health_check_path = "/health.html"
health_check_interval = 30
health_check_timeout = 2
health_check_healthy_threshold = 2
health_check_unhealthy_threshold = 2
health_check_protocol = "HTTP"
domain_name="vpkdevops.online"
hostname="webapp"